// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyFormat.
const (
	MARKDOWN BodyFormat = "MARKDOWN"
	TEXT     BodyFormat = "TEXT"
)

// Valid indicates whether the value is a known member of the BodyFormat enum.
func (e BodyFormat) Valid() bool {
	switch e {
	case MARKDOWN:
		return true
	case TEXT:
		return true
	default:
		return false
	}
}

// Defines values for Lifecycle.
const (
	PERMANENT Lifecycle = "PERMANENT"
	TEMPORARY Lifecycle = "TEMPORARY"
)

// Valid indicates whether the value is a known member of the Lifecycle enum.
func (e Lifecycle) Valid() bool {
	switch e {
	case PERMANENT:
		return true
	case TEMPORARY:
		return true
	default:
		return false
	}
}

// Defines values for UploadStatus.
const (
	COMPLETED  UploadStatus = "COMPLETED"
	COMPLETING UploadStatus = "COMPLETING"
	CREATED    UploadStatus = "CREATED"
	EXPIRED    UploadStatus = "EXPIRED"
	FAILED     UploadStatus = "FAILED"
	UPLOADING  UploadStatus = "UPLOADING"
)

// Valid indicates whether the value is a known member of the UploadStatus enum.
func (e UploadStatus) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case COMPLETING:
		return true
	case CREATED:
		return true
	case EXPIRED:
		return true
	case FAILED:
		return true
	case UPLOADING:
		return true
	default:
		return false
	}
}

// AddAttachmentsRequest defines model for AddAttachmentsRequest.
type AddAttachmentsRequest struct {
	ExpectedVersion int64                `json:"expectedVersion"`
	UploadIds       []openapi_types.UUID `json:"uploadIds"`
}

// AttachmentSummary defines model for AttachmentSummary.
type AttachmentSummary struct {
	ClientMime       *string            `json:"clientMime"`
	DetectedMime     string             `json:"detectedMime"`
	DisplayOrder     int                `json:"displayOrder"`
	Id               openapi_types.UUID `json:"id"`
	OriginalFilename string             `json:"originalFilename"`
	SizeBytes        int64              `json:"sizeBytes"`
}

// AuthBootstrap defines model for AuthBootstrap.
type AuthBootstrap struct {
	CsrfToken string  `json:"csrfToken"`
	Device    Device  `json:"device"`
	Session   Session `json:"session"`
	User      User    `json:"user"`
}

// BodyFormat defines model for BodyFormat.
type BodyFormat string

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	Body       *string               `json:"body,omitempty"`
	BodyFormat *BodyFormat           `json:"bodyFormat,omitempty"`
	Lifecycle  *Lifecycle            `json:"lifecycle,omitempty"`
	Sensitive  *bool                 `json:"sensitive,omitempty"`
	TagIds     *[]openapi_types.UUID `json:"tagIds,omitempty"`
	UploadIds  *[]openapi_types.UUID `json:"uploadIds,omitempty"`
}

// CreateUploadRequest defines model for CreateUploadRequest.
type CreateUploadRequest struct {
	ClientMime       *string `json:"clientMime,omitempty"`
	ExpectedSize     int64   `json:"expectedSize"`
	OriginalFilename string  `json:"originalFilename"`
}

// Device defines model for Device.
type Device struct {
	FirstSeenAt time.Time          `json:"firstSeenAt"`
	Id          openapi_types.UUID `json:"id"`
	LastSeenAt  time.Time          `json:"lastSeenAt"`
	Name        string             `json:"name"`
	UserAgent   string             `json:"userAgent"`
}

// DirectSendRequest defines model for DirectSendRequest.
type DirectSendRequest struct {
	Body            *string               `json:"body,omitempty"`
	BodyFormat      *BodyFormat           `json:"bodyFormat,omitempty"`
	RecipientUserId openapi_types.UUID    `json:"recipientUserId"`
	Sensitive       *bool                 `json:"sensitive,omitempty"`
	UploadIds       *[]openapi_types.UUID `json:"uploadIds,omitempty"`
}

// EditMessageRequest defines model for EditMessageRequest.
type EditMessageRequest struct {
	Body             *string     `json:"body,omitempty"`
	BodyFormat       *BodyFormat `json:"bodyFormat,omitempty"`
	DetectedLanguage *string     `json:"detectedLanguage,omitempty"`
	DetectedType     *string     `json:"detectedType,omitempty"`
	ExpectedVersion  int64       `json:"expectedVersion"`
}

// EditSensitiveBodyRequest defines model for EditSensitiveBodyRequest.
type EditSensitiveBodyRequest struct {
	Body            string `json:"body"`
	ExpectedVersion int64  `json:"expectedVersion"`
}

// Error defines model for Error.
type Error struct {
	Code    string      `json:"code"`
	Details interface{} `json:"details"`
	Message string      `json:"message"`
	TraceId string      `json:"traceId"`
}

// FavoriteRequest defines model for FavoriteRequest.
type FavoriteRequest struct {
	ExpectedVersion int64 `json:"expectedVersion"`
	Favorite        bool  `json:"favorite"`
}

// ForwardRequest defines model for ForwardRequest.
type ForwardRequest struct {
	ExpectedVersion int64              `json:"expectedVersion"`
	RecipientUserId openapi_types.UUID `json:"recipientUserId"`
}

// Lifecycle defines model for Lifecycle.
type Lifecycle string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	DeviceId   *openapi_types.UUID `json:"deviceId,omitempty"`
	DeviceName *string             `json:"deviceName,omitempty"`
	Password   string              `json:"password"`
	Username   string              `json:"username"`
}

// Message defines model for Message.
type Message struct {
	Attachments      []AttachmentSummary `json:"attachments"`
	Body             *string             `json:"body"`
	BodyFormat       BodyFormat          `json:"bodyFormat"`
	CreatedAt        time.Time           `json:"createdAt"`
	DetectedLanguage *string             `json:"detectedLanguage,omitempty"`
	DetectedType     *string             `json:"detectedType,omitempty"`
	ExpiresAt        *time.Time          `json:"expiresAt,omitempty"`
	Favorite         bool                `json:"favorite"`
	Id               openapi_types.UUID  `json:"id"`
	Lifecycle        Lifecycle           `json:"lifecycle"`
	PurgeAt          *time.Time          `json:"purgeAt,omitempty"`
	Sensitive        bool                `json:"sensitive"`
	SourceMessageId  *openapi_types.UUID `json:"sourceMessageId,omitempty"`
	SourceUserId     *openapi_types.UUID `json:"sourceUserId,omitempty"`
	Tags             []Tag               `json:"tags"`
	TrashedAt        *time.Time          `json:"trashedAt,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	Version          int64               `json:"version"`
}

// MessageDeliveryReceipt defines model for MessageDeliveryReceipt.
type MessageDeliveryReceipt struct {
	CreatedAt time.Time          `json:"createdAt"`
	ExpiresAt time.Time          `json:"expiresAt"`
	MessageId openapi_types.UUID `json:"messageId"`
}

// MessageList defines model for MessageList.
type MessageList struct {
	Items      []MessageSummary `json:"items"`
	NextCursor *string          `json:"nextCursor"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	AttachmentCount  int                 `json:"attachmentCount"`
	Attachments      []AttachmentSummary `json:"attachments"`
	Body             *string             `json:"body"`
	BodyFormat       BodyFormat          `json:"bodyFormat"`
	BodyPreview      *string             `json:"bodyPreview"`
	BodyTruncated    bool                `json:"bodyTruncated"`
	CreatedAt        time.Time           `json:"createdAt"`
	DetectedLanguage *string             `json:"detectedLanguage,omitempty"`
	DetectedType     *string             `json:"detectedType,omitempty"`
	ExpiresAt        *time.Time          `json:"expiresAt,omitempty"`
	Favorite         bool                `json:"favorite"`
	Id               openapi_types.UUID  `json:"id"`
	Lifecycle        Lifecycle           `json:"lifecycle"`
	PurgeAt          *time.Time          `json:"purgeAt,omitempty"`
	Sensitive        bool                `json:"sensitive"`
	SourceMessageId  *openapi_types.UUID `json:"sourceMessageId,omitempty"`
	SourceUserId     *openapi_types.UUID `json:"sourceUserId,omitempty"`
	Tags             []Tag               `json:"tags"`
	TrashedAt        *time.Time          `json:"trashedAt,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	Version          int64               `json:"version"`
}

// PasswordChangeRequest defines model for PasswordChangeRequest.
type PasswordChangeRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// RenameDeviceRequest defines model for RenameDeviceRequest.
type RenameDeviceRequest struct {
	Name string `json:"name"`
}

// ReplaceMessageTagsRequest defines model for ReplaceMessageTagsRequest.
type ReplaceMessageTagsRequest struct {
	ExpectedVersion int64                `json:"expectedVersion"`
	TagIds          []openapi_types.UUID `json:"tagIds"`
}

// SensitiveBody defines model for SensitiveBody.
type SensitiveBody struct {
	Body    string `json:"body"`
	Version int64  `json:"version"`
}

// SensitiveRequest defines model for SensitiveRequest.
type SensitiveRequest struct {
	ExpectedVersion int64 `json:"expectedVersion"`
	Sensitive       bool  `json:"sensitive"`
}

// Session defines model for Session.
type Session struct {
	AbsoluteExpiresAt time.Time          `json:"absoluteExpiresAt"`
	CreatedAt         time.Time          `json:"createdAt"`
	Current           bool               `json:"current"`
	DeviceId          openapi_types.UUID `json:"deviceId"`
	ExpiresAt         time.Time          `json:"expiresAt"`
	Id                openapi_types.UUID `json:"id"`
	LastIp            *string            `json:"lastIp,omitempty"`
	LastSeenAt        time.Time          `json:"lastSeenAt"`
}

// Tag defines model for Tag.
type Tag struct {
	Color     string             `json:"color"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// TagRequest defines model for TagRequest.
type TagRequest struct {
	Color string `json:"color"`
	Name  string `json:"name"`
}

// UpdateTagRequest defines model for UpdateTagRequest.
type UpdateTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// UploadSession defines model for UploadSession.
type UploadSession struct {
	ChunkSize        int64              `json:"chunkSize"`
	ClientMime       *string            `json:"clientMime,omitempty"`
	CompletedParts   []int              `json:"completedParts"`
	CreatedAt        time.Time          `json:"createdAt"`
	ExpectedSize     int64              `json:"expectedSize"`
	ExpiresAt        time.Time          `json:"expiresAt"`
	Id               openapi_types.UUID `json:"id"`
	OriginalFilename string             `json:"originalFilename"`
	PartCount        int                `json:"partCount"`
	Status           UploadStatus       `json:"status"`
	UpdatedAt        time.Time          `json:"updatedAt"`
}

// UploadStatus defines model for UploadStatus.
type UploadStatus string

// User defines model for User.
type User struct {
	DisplayName string             `json:"displayName"`
	Id          openapi_types.UUID `json:"id"`
	IsAdmin     bool               `json:"isAdmin"`
	Username    string             `json:"username"`
}

// VersionRequest defines model for VersionRequest.
type VersionRequest struct {
	ExpectedVersion int64 `json:"expectedVersion"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// DeviceId defines model for DeviceId.
type DeviceId = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// MessageId defines model for MessageId.
type MessageId = openapi_types.UUID

// PartNumber defines model for PartNumber.
type PartNumber = int

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// TagId defines model for TagId.
type TagId = openapi_types.UUID

// UploadId defines model for UploadId.
type UploadId = openapi_types.UUID

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	Lifecycle *Lifecycle            `form:"lifecycle,omitempty" json:"lifecycle,omitempty"`
	Favorite  *bool                 `form:"favorite,omitempty" json:"favorite,omitempty"`
	TagId     *[]openapi_types.UUID `form:"tagId,omitempty" json:"tagId,omitempty"`
	Cursor    *Cursor               `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit                `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateMessageParams defines parameters for CreateMessage.
type CreateMessageParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DirectSendMessageParams defines parameters for DirectSendMessage.
type DirectSendMessageParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ForwardMessageParams defines parameters for ForwardMessage.
type ForwardMessageParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SearchMessagesParams defines parameters for SearchMessages.
type SearchMessagesParams struct {
	Q             *string               `form:"q,omitempty" json:"q,omitempty"`
	Lifecycle     *Lifecycle            `form:"lifecycle,omitempty" json:"lifecycle,omitempty"`
	Favorite      *bool                 `form:"favorite,omitempty" json:"favorite,omitempty"`
	TagId         *[]openapi_types.UUID `form:"tagId,omitempty" json:"tagId,omitempty"`
	Type          *string               `form:"type,omitempty" json:"type,omitempty"`
	CreatedAfter  *time.Time            `form:"createdAfter,omitempty" json:"createdAfter,omitempty"`
	CreatedBefore *time.Time            `form:"createdBefore,omitempty" json:"createdBefore,omitempty"`
	Cursor        *Cursor               `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *Limit                `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTrashParams defines parameters for ListTrash.
type ListTrashParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = PasswordChangeRequest

// RenameDeviceJSONRequestBody defines body for RenameDevice for application/json ContentType.
type RenameDeviceJSONRequestBody = RenameDeviceRequest

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = CreateMessageRequest

// DirectSendMessageJSONRequestBody defines body for DirectSendMessage for application/json ContentType.
type DirectSendMessageJSONRequestBody = DirectSendRequest

// EditMessageJSONRequestBody defines body for EditMessage for application/json ContentType.
type EditMessageJSONRequestBody = EditMessageRequest

// AddMessageAttachmentsJSONRequestBody defines body for AddMessageAttachments for application/json ContentType.
type AddMessageAttachmentsJSONRequestBody = AddAttachmentsRequest

// RemoveMessageAttachmentJSONRequestBody defines body for RemoveMessageAttachment for application/json ContentType.
type RemoveMessageAttachmentJSONRequestBody = VersionRequest

// SetMessageFavoriteJSONRequestBody defines body for SetMessageFavorite for application/json ContentType.
type SetMessageFavoriteJSONRequestBody = FavoriteRequest

// ForwardMessageJSONRequestBody defines body for ForwardMessage for application/json ContentType.
type ForwardMessageJSONRequestBody = ForwardRequest

// MakeMessagePermanentJSONRequestBody defines body for MakeMessagePermanent for application/json ContentType.
type MakeMessagePermanentJSONRequestBody = VersionRequest

// SetMessageSensitiveJSONRequestBody defines body for SetMessageSensitive for application/json ContentType.
type SetMessageSensitiveJSONRequestBody = SensitiveRequest

// EditSensitiveBodyJSONRequestBody defines body for EditSensitiveBody for application/json ContentType.
type EditSensitiveBodyJSONRequestBody = EditSensitiveBodyRequest

// ReplaceMessageTagsJSONRequestBody defines body for ReplaceMessageTags for application/json ContentType.
type ReplaceMessageTagsJSONRequestBody = ReplaceMessageTagsRequest

// TrashMessageJSONRequestBody defines body for TrashMessage for application/json ContentType.
type TrashMessageJSONRequestBody = VersionRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = TagRequest

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagRequest

// RestoreMessageJSONRequestBody defines body for RestoreMessage for application/json ContentType.
type RestoreMessageJSONRequestBody = VersionRequest

// CreateUploadJSONRequestBody defines body for CreateUpload for application/json ContentType.
type CreateUploadJSONRequestBody = CreateUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /attachments/{attachmentId}/download)
	DownloadAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)

	// (GET /attachments/{attachmentId}/preview)
	PreviewAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)

	// (GET /attachments/{attachmentId}/thumbnail)
	GetAttachmentThumbnail(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password/change)
	ChangePassword(w http.ResponseWriter, r *http.Request)

	// (GET /auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)

	// (GET /devices)
	ListDevices(w http.ResponseWriter, r *http.Request)

	// (PATCH /devices/{deviceId})
	RenameDevice(w http.ResponseWriter, r *http.Request, deviceId DeviceId)

	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request)

	// (GET /messages)
	ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams)

	// (POST /messages)
	CreateMessage(w http.ResponseWriter, r *http.Request, params CreateMessageParams)

	// (POST /messages/direct-send)
	DirectSendMessage(w http.ResponseWriter, r *http.Request, params DirectSendMessageParams)

	// (GET /messages/{messageId})
	GetMessage(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (PATCH /messages/{messageId})
	EditMessage(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /messages/{messageId}/attachments)
	AddMessageAttachments(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (DELETE /messages/{messageId}/attachments/{attachmentId})
	RemoveMessageAttachment(w http.ResponseWriter, r *http.Request, messageId MessageId, attachmentId AttachmentId)

	// (POST /messages/{messageId}/favorite)
	SetMessageFavorite(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /messages/{messageId}/forward)
	ForwardMessage(w http.ResponseWriter, r *http.Request, messageId MessageId, params ForwardMessageParams)

	// (POST /messages/{messageId}/make-permanent)
	MakeMessagePermanent(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /messages/{messageId}/sensitive)
	SetMessageSensitive(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (GET /messages/{messageId}/sensitive-body)
	RevealSensitiveBody(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (PUT /messages/{messageId}/sensitive-body)
	EditSensitiveBody(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (PUT /messages/{messageId}/tags)
	ReplaceMessageTags(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /messages/{messageId}/trash)
	TrashMessage(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (GET /search)
	SearchMessages(w http.ResponseWriter, r *http.Request, params SearchMessagesParams)

	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)

	// (DELETE /sessions/{sessionId})
	RevokeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)

	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request)

	// (POST /tags)
	CreateTag(w http.ResponseWriter, r *http.Request)

	// (DELETE /tags/{tagId})
	DeleteTag(w http.ResponseWriter, r *http.Request, tagId TagId)

	// (PATCH /tags/{tagId})
	UpdateTag(w http.ResponseWriter, r *http.Request, tagId TagId)

	// (GET /trash)
	ListTrash(w http.ResponseWriter, r *http.Request, params ListTrashParams)

	// (DELETE /trash/{messageId})
	PermanentlyDeleteMessage(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /trash/{messageId}/restore)
	RestoreMessage(w http.ResponseWriter, r *http.Request, messageId MessageId)

	// (POST /uploads)
	CreateUpload(w http.ResponseWriter, r *http.Request)

	// (GET /uploads/{uploadId})
	GetUpload(w http.ResponseWriter, r *http.Request, uploadId UploadId)

	// (POST /uploads/{uploadId}/complete)
	CompleteUpload(w http.ResponseWriter, r *http.Request, uploadId UploadId)

	// (PUT /uploads/{uploadId}/parts/{partNumber})
	PutUploadPart(w http.ResponseWriter, r *http.Request, uploadId UploadId, partNumber PartNumber)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /attachments/{attachmentId}/download)
func (_ Unimplemented) DownloadAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /attachments/{attachmentId}/preview)
func (_ Unimplemented) PreviewAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /attachments/{attachmentId}/thumbnail)
func (_ Unimplemented) GetAttachmentThumbnail(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password/change)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/session)
func (_ Unimplemented) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /devices)
func (_ Unimplemented) ListDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /devices/{deviceId})
func (_ Unimplemented) RenameDevice(w http.ResponseWriter, r *http.Request, deviceId DeviceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages)
func (_ Unimplemented) CreateMessage(w http.ResponseWriter, r *http.Request, params CreateMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/direct-send)
func (_ Unimplemented) DirectSendMessage(w http.ResponseWriter, r *http.Request, params DirectSendMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /messages/{messageId})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /messages/{messageId})
func (_ Unimplemented) EditMessage(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/attachments)
func (_ Unimplemented) AddMessageAttachments(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /messages/{messageId}/attachments/{attachmentId})
func (_ Unimplemented) RemoveMessageAttachment(w http.ResponseWriter, r *http.Request, messageId MessageId, attachmentId AttachmentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/favorite)
func (_ Unimplemented) SetMessageFavorite(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/forward)
func (_ Unimplemented) ForwardMessage(w http.ResponseWriter, r *http.Request, messageId MessageId, params ForwardMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/make-permanent)
func (_ Unimplemented) MakeMessagePermanent(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/sensitive)
func (_ Unimplemented) SetMessageSensitive(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /messages/{messageId}/sensitive-body)
func (_ Unimplemented) RevealSensitiveBody(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /messages/{messageId}/sensitive-body)
func (_ Unimplemented) EditSensitiveBody(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /messages/{messageId}/tags)
func (_ Unimplemented) ReplaceMessageTags(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /messages/{messageId}/trash)
func (_ Unimplemented) TrashMessage(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /search)
func (_ Unimplemented) SearchMessages(w http.ResponseWriter, r *http.Request, params SearchMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /sessions/{sessionId})
func (_ Unimplemented) RevokeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /tags)
func (_ Unimplemented) ListTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /tags)
func (_ Unimplemented) CreateTag(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /tags/{tagId})
func (_ Unimplemented) DeleteTag(w http.ResponseWriter, r *http.Request, tagId TagId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /tags/{tagId})
func (_ Unimplemented) UpdateTag(w http.ResponseWriter, r *http.Request, tagId TagId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /trash)
func (_ Unimplemented) ListTrash(w http.ResponseWriter, r *http.Request, params ListTrashParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /trash/{messageId})
func (_ Unimplemented) PermanentlyDeleteMessage(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /trash/{messageId}/restore)
func (_ Unimplemented) RestoreMessage(w http.ResponseWriter, r *http.Request, messageId MessageId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /uploads)
func (_ Unimplemented) CreateUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /uploads/{uploadId})
func (_ Unimplemented) GetUpload(w http.ResponseWriter, r *http.Request, uploadId UploadId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /uploads/{uploadId}/complete)
func (_ Unimplemented) CompleteUpload(w http.ResponseWriter, r *http.Request, uploadId UploadId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /uploads/{uploadId}/parts/{partNumber})
func (_ Unimplemented) PutUploadPart(w http.ResponseWriter, r *http.Request, uploadId UploadId, partNumber PartNumber) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DownloadAttachment operation middleware
func (siw *ServerInterfaceWrapper) DownloadAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewAttachment operation middleware
func (siw *ServerInterfaceWrapper) PreviewAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachmentThumbnail operation middleware
func (siw *ServerInterfaceWrapper) GetAttachmentThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachmentThumbnail(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameDevice operation middleware
func (siw *ServerInterfaceWrapper) RenameDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId DeviceId

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", chi.URLParam(r, "deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "lifecycle" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lifecycle", r.URL.Query(), &params.Lifecycle, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lifecycle"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lifecycle", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "favorite" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "favorite", r.URL.Query(), &params.Favorite, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "favorite"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "favorite", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagId", r.URL.Query(), &params.TagId, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMessage operation middleware
func (siw *ServerInterfaceWrapper) CreateMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateMessageParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DirectSendMessage operation middleware
func (siw *ServerInterfaceWrapper) DirectSendMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DirectSendMessageParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DirectSendMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditMessage operation middleware
func (siw *ServerInterfaceWrapper) EditMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditMessage(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddMessageAttachments operation middleware
func (siw *ServerInterfaceWrapper) AddMessageAttachments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddMessageAttachments(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMessageAttachment operation middleware
func (siw *ServerInterfaceWrapper) RemoveMessageAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", chi.URLParam(r, "attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMessageAttachment(w, r, messageId, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetMessageFavorite operation middleware
func (siw *ServerInterfaceWrapper) SetMessageFavorite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetMessageFavorite(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForwardMessage operation middleware
func (siw *ServerInterfaceWrapper) ForwardMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ForwardMessageParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForwardMessage(w, r, messageId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MakeMessagePermanent operation middleware
func (siw *ServerInterfaceWrapper) MakeMessagePermanent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MakeMessagePermanent(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetMessageSensitive operation middleware
func (siw *ServerInterfaceWrapper) SetMessageSensitive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetMessageSensitive(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevealSensitiveBody operation middleware
func (siw *ServerInterfaceWrapper) RevealSensitiveBody(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevealSensitiveBody(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditSensitiveBody operation middleware
func (siw *ServerInterfaceWrapper) EditSensitiveBody(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditSensitiveBody(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceMessageTags operation middleware
func (siw *ServerInterfaceWrapper) ReplaceMessageTags(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceMessageTags(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TrashMessage operation middleware
func (siw *ServerInterfaceWrapper) TrashMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TrashMessage(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchMessages operation middleware
func (siw *ServerInterfaceWrapper) SearchMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMessagesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lifecycle" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lifecycle", r.URL.Query(), &params.Lifecycle, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lifecycle"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lifecycle", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "favorite" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "favorite", r.URL.Query(), &params.Favorite, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "favorite"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "favorite", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagId", r.URL.Query(), &params.TagId, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdAfter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdAfter", r.URL.Query(), &params.CreatedAfter, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdAfter"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdAfter", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdBefore" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdBefore", r.URL.Query(), &params.CreatedBefore, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdBefore"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdBefore", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTag operation middleware
func (siw *ServerInterfaceWrapper) CreateTag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tagId" -------------
	var tagId TagId

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", chi.URLParam(r, "tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTag(w, r, tagId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTag operation middleware
func (siw *ServerInterfaceWrapper) UpdateTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tagId" -------------
	var tagId TagId

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", chi.URLParam(r, "tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTag(w, r, tagId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrash operation middleware
func (siw *ServerInterfaceWrapper) ListTrash(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTrashParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrash(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PermanentlyDeleteMessage operation middleware
func (siw *ServerInterfaceWrapper) PermanentlyDeleteMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PermanentlyDeleteMessage(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreMessage operation middleware
func (siw *ServerInterfaceWrapper) RestoreMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "messageId" -------------
	var messageId MessageId

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreMessage(w, r, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUpload operation middleware
func (siw *ServerInterfaceWrapper) GetUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uploadId" -------------
	var uploadId UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "uploadId", chi.URLParam(r, "uploadId"), &uploadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uploadId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpload(w, r, uploadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uploadId" -------------
	var uploadId UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "uploadId", chi.URLParam(r, "uploadId"), &uploadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uploadId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteUpload(w, r, uploadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutUploadPart operation middleware
func (siw *ServerInterfaceWrapper) PutUploadPart(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uploadId" -------------
	var uploadId UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "uploadId", chi.URLParam(r, "uploadId"), &uploadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uploadId", Err: err})
		return
	}

	// ------------- Path parameter "partNumber" -------------
	var partNumber PartNumber

	err = runtime.BindStyledParameterWithOptions("simple", "partNumber", chi.URLParam(r, "partNumber"), &partNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partNumber", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUploadPart(w, r, uploadId, partNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/session", wrapper.GetAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password/change", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sessions/{sessionId}", wrapper.RevokeSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.ListDevices)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/devices/{deviceId}", wrapper.RenameDevice)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/uploads", wrapper.CreateUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/uploads/{uploadId}", wrapper.GetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/uploads/{uploadId}/parts/{partNumber}", wrapper.PutUploadPart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/uploads/{uploadId}/complete", wrapper.CompleteUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages", wrapper.CreateMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/direct-send", wrapper.DirectSendMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages/{messageId}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/messages/{messageId}", wrapper.EditMessage)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/messages/{messageId}/tags", wrapper.ReplaceMessageTags)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/attachments", wrapper.AddMessageAttachments)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/messages/{messageId}/attachments/{attachmentId}", wrapper.RemoveMessageAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/attachments/{attachmentId}/download", wrapper.DownloadAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/attachments/{attachmentId}/preview", wrapper.PreviewAttachment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/attachments/{attachmentId}/thumbnail", wrapper.GetAttachmentThumbnail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/make-permanent", wrapper.MakeMessagePermanent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/favorite", wrapper.SetMessageFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/trash", wrapper.TrashMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/sensitive", wrapper.SetMessageSensitive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages/{messageId}/sensitive-body", wrapper.RevealSensitiveBody)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/messages/{messageId}/sensitive-body", wrapper.EditSensitiveBody)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages/{messageId}/forward", wrapper.ForwardMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trash", wrapper.ListTrash)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trash/{messageId}/restore", wrapper.RestoreMessage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trash/{messageId}", wrapper.PermanentlyDeleteMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.ListTags)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tags", wrapper.CreateTag)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tags/{tagId}", wrapper.DeleteTag)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/tags/{tagId}", wrapper.UpdateTag)
	})

	return r
}
