import { expect, test } from '@playwright/test'
import { alice, login, marker } from './helpers'

for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
  test.describe(`message feedback and editing at ${viewport.width}px`, () => {
    test.use({ viewport })
    test('preserves rich text through send/edit and dismisses tags and image previews', async ({ page }) => {
      const title = marker('rich-text')
      await login(page, alice)
      const composer = page.locator('.composer')
      await composer.getByLabel('标题（可选）').fill(title)
      await composer.locator('textarea').fill('格式内容')
      await composer.locator('textarea').press('Control+a')
      await composer.getByRole('button', { name: '加粗', exact: true }).click()
      const source = '**格式内容**\n\n*斜体*\n\n- 列表\n\n> 引用\n\n[链接](https://example.com)\n\n```js\nconst value = 1\n```\n\n![正文图](https://image.test/inline.png)'
      await composer.locator('textarea').fill(source)
      await composer.getByRole('button', { name: '预览', exact: true }).click()
      await expect(composer.locator('.editor-preview strong')).toHaveText('格式内容')
      await composer.getByRole('button', { name: '继续编辑' }).click()
      await composer.locator('textarea').dispatchEvent('compositionstart')
      await composer.locator('textarea').press('Control+Enter')
      await expect(composer.locator('textarea')).toHaveValue(source)
      await composer.locator('textarea').dispatchEvent('compositionend')
      const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1EAAAAASUVORK5CYII=', 'base64')
      await composer.locator('input[type=file]').setInputFiles(['preview.png', 'second.png', 'third.png', 'fourth.png'].map(name => ({ name, mimeType: 'image/png', buffer: png })))
      await expect(composer.getByRole('button', { name: '发送', exact: true })).toBeEnabled()
      await composer.getByRole('button', { name: '发送', exact: true }).click()
      const card = page.locator('.message-card', { hasText: title })
      await expect(card.locator('.safe-markdown strong')).toHaveText('格式内容')
      await card.getByRole('button', { name: '添加标签', exact: true }).click()
      await card.getByLabel('新建标签名称').fill('输入不中断')
      await expect(card.locator('.tag-popover')).toBeVisible()
      await page.keyboard.press('Escape')
      await expect(card.locator('.tag-popover')).toHaveCount(0)
      await card.getByRole('button', { name: '添加标签', exact: true }).click()
      await page.locator('.composer').click({ position: { x: 5, y: 5 } })
      await expect(card.locator('.tag-popover')).toHaveCount(0)
      await page.route('https://image.test/**', route => route.fulfill({ contentType: 'image/png', body: png }))
      await card.getByRole('button', { name: '预览 preview.png' }).click()
      const preview = page.getByRole('dialog', { name: '图片预览' })
      await expect(preview.locator('img')).toBeVisible()
      await expect(preview.locator('header')).toContainText('/ 5')
      await preview.getByRole('button', { name: '上一张' }).click()
      await expect(preview.locator('header')).toContainText('正文图')
      await page.keyboard.press('Escape')
      await expect(preview).toHaveCount(0)
      await card.getByRole('button', { name: /打开内容/ }).click()
      const detail = page.locator('.message-inspector')
      await detail.getByRole('button', { name: '编辑', exact: true }).click()
      await expect(detail.locator('textarea')).toHaveValue(source)
      await detail.locator('textarea').fill(source + '\n\n再次编辑')
      await detail.getByRole('button', { name: '保存', exact: true }).click()
      await expect(detail.locator('.safe-markdown strong')).toHaveText('格式内容')
      await detail.getByRole('button', { name: '编辑', exact: true }).click()
      await expect(detail.locator('textarea')).toHaveValue(source + '\n\n再次编辑')
    })
  })
}
